//===========================================================================
// 
// 11111
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Map Author: 44444
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************

globals
    // Generated
    trigger                 gg_trg_Melee_Initialization = null
endglobals

function InitGlobals takes nothing returns nothing
endfunction

//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************

//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************

//===========================================================================
function CreateUnitsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'Hblm', -233.3, -328.0, 181.950, 'Hblm' )
endfunction

//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
endfunction

//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
    call CreateUnitsForPlayer0(  )
endfunction

//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreatePlayerBuildings(  )
    call CreatePlayerUnits(  )
endfunction

//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************

//===========================================================================
// Trigger: Melee Initialization
//
// Default melee game initialization for all players
//===========================================================================
function Trig_Melee_Initialization_Actions takes nothing returns nothing
    call MeleeStartingVisibility(  )
    call MeleeStartingHeroLimit(  )
    call MeleeGrantHeroItems(  )
    call MeleeStartingResources(  )
    call MeleeClearExcessUnits(  )
    call MeleeStartingUnits(  )
    call MeleeStartingAI(  )
    call MeleeInitVictoryDefeat(  )
endfunction

//===========================================================================
function InitTrig_Melee_Initialization takes nothing returns nothing
    set gg_trg_Melee_Initialization = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Melee_Initialization, function Trig_Melee_Initialization_Actions )
endfunction

//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_Melee_Initialization(  )
endfunction

//===========================================================================
function RunInitializationTriggers takes nothing returns nothing
    call ConditionalTriggerExecute( gg_trg_Melee_Initialization )
endfunction

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation( Player(0), 0 )
    call SetPlayerColor( Player(0), ConvertPlayerColor(0) )
    call SetPlayerRacePreference( Player(0), RACE_PREF_HUMAN )
    call SetPlayerRaceSkin( Player(0), RACE_PREF_ORC )
    call SetPlayerRaceSelectable( Player(0), false )
    call SetPlayerController( Player(0), MAP_CONTROL_USER )

    // Player 1
    call SetPlayerStartLocation( Player(1), 1 )
    call ForcePlayerStartLocation( Player(1), 1 )
    call SetPlayerColor( Player(1), ConvertPlayerColor(1) )
    call SetPlayerRacePreference( Player(1), RACE_PREF_ORC )
    call SetPlayerRaceSkin( Player(1), RACE_PREF_UNDEAD )
    call SetPlayerRaceSelectable( Player(1), false )
    call SetPlayerController( Player(1), MAP_CONTROL_USER )

    // Player 2
    call SetPlayerStartLocation( Player(2), 2 )
    call SetPlayerColor( Player(2), ConvertPlayerColor(2) )
    call SetPlayerRacePreference( Player(2), RACE_PREF_UNDEAD )
    call SetPlayerRaceSkin( Player(2), RACE_PREF_USER_SELECTABLE )
    call SetPlayerRaceSelectable( Player(2), false )
    call SetPlayerController( Player(2), MAP_CONTROL_COMPUTER )

    // Player 3
    call SetPlayerStartLocation( Player(3), 3 )
    call ForcePlayerStartLocation( Player(3), 3 )
    call SetPlayerColor( Player(3), ConvertPlayerColor(3) )
    call SetPlayerRacePreference( Player(3), RACE_PREF_NIGHTELF )
    call SetPlayerRaceSkin( Player(3), RACE_PREF_USER_SELECTABLE )
    call SetPlayerRaceSelectable( Player(3), false )
    call SetPlayerController( Player(3), MAP_CONTROL_COMPUTER )

    // Player 4
    call SetPlayerStartLocation( Player(4), 4 )
    call SetPlayerColor( Player(4), ConvertPlayerColor(4) )
    call SetPlayerRacePreference( Player(4), RACE_PREF_HUMAN )
    call SetPlayerRaceSkin( Player(4), RACE_PREF_USER_SELECTABLE )
    call SetPlayerRaceSelectable( Player(4), false )
    call SetPlayerController( Player(4), MAP_CONTROL_NEUTRAL )

    // Player 5
    call SetPlayerStartLocation( Player(5), 5 )
    call SetPlayerColor( Player(5), ConvertPlayerColor(5) )
    call SetPlayerRacePreference( Player(5), RACE_PREF_ORC )
    call SetPlayerRaceSkin( Player(5), RACE_PREF_USER_SELECTABLE )
    call SetPlayerRaceSelectable( Player(5), false )
    call SetPlayerController( Player(5), MAP_CONTROL_RESCUABLE )
    call SetPlayerAlliance( Player(5), Player(0), ALLIANCE_RESCUABLE, true )
    call SetPlayerAlliance( Player(5), Player(1), ALLIANCE_RESCUABLE, true )

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_016
    call SetPlayerTeam( Player(0), 0 )
    call SetPlayerState( Player(0), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(1), 0 )
    call SetPlayerState( Player(1), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(2), 0 )
    call SetPlayerState( Player(2), PLAYER_STATE_ALLIED_VICTORY, 1 )

    // Force: TRIGSTR_017
    call SetPlayerTeam( Player(3), 1 )
    call SetPlayerTeam( Player(4), 1 )
    call SetPlayerTeam( Player(5), 1 )

    //   Allied
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(4), true )

    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(4), true )

    //   Shared Control
    call SetPlayerAllianceStateControlBJ( Player(3), Player(4), true )
    call SetPlayerAllianceStateControlBJ( Player(3), Player(5), true )
    call SetPlayerAllianceStateControlBJ( Player(4), Player(3), true )
    call SetPlayerAllianceStateControlBJ( Player(4), Player(5), true )
    call SetPlayerAllianceStateControlBJ( Player(5), Player(3), true )
    call SetPlayerAllianceStateControlBJ( Player(5), Player(4), true )

    //   Shared Advanced Control
    call SetPlayerAllianceStateFullControlBJ( Player(3), Player(4), true )
    call SetPlayerAllianceStateFullControlBJ( Player(3), Player(5), true )
    call SetPlayerAllianceStateFullControlBJ( Player(4), Player(3), true )
    call SetPlayerAllianceStateFullControlBJ( Player(4), Player(5), true )
    call SetPlayerAllianceStateFullControlBJ( Player(5), Player(3), true )
    call SetPlayerAllianceStateFullControlBJ( Player(5), Player(4), true )

endfunction

function InitAllyPriorities takes nothing returns nothing

    call SetStartLocPrioCount( 0, 1 )
    call SetStartLocPrio( 0, 0, 1, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 1, 1 )
    call SetStartLocPrio( 1, 0, 0, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 2, 4 )
    call SetStartLocPrio( 2, 0, 0, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 2, 1, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 2, 2, 3, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 2, 3, 5, MAP_LOC_PRIO_LOW )

    call SetEnemyStartLocPrioCount( 3, 4 )
    call SetEnemyStartLocPrio( 3, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetEnemyStartLocPrio( 3, 1, 1, MAP_LOC_PRIO_HIGH )
    call SetEnemyStartLocPrio( 3, 2, 2, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 4, 5 )
    call SetStartLocPrio( 4, 0, 0, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 4, 1, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 4, 2, 2, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 4, 3, 3, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 4, 4, 5, MAP_LOC_PRIO_HIGH )

    call SetEnemyStartLocPrioCount( 4, 3 )
    call SetEnemyStartLocPrio( 4, 0, 1, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 4, 1, 2, MAP_LOC_PRIO_LOW )

    call SetStartLocPrioCount( 5, 3 )
    call SetStartLocPrio( 5, 0, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 5, 1, 2, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 5, 2, 4, MAP_LOC_PRIO_LOW )

    call SetEnemyStartLocPrioCount( 5, 6 )
    call SetEnemyStartLocPrio( 5, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetEnemyStartLocPrio( 5, 1, 1, MAP_LOC_PRIO_HIGH )
    call SetEnemyStartLocPrio( 5, 2, 2, MAP_LOC_PRIO_HIGH )
    call SetEnemyStartLocPrio( 5, 3, 3, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 5, 4, 4, MAP_LOC_PRIO_LOW )
endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    local weathereffect we
    call SetCameraBounds( -3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )
    call SetDayNightModels( "Environment\\DNC\\DNCAshenvale\\DNCAshenvaleTerrain\\DNCAshenvaleTerrain.mdl", "Environment\\DNC\\DNCAshenvale\\DNCAshenvaleUnit\\DNCAshenvaleUnit.mdl" )
    call SetTerrainFogExV( 0, 3000.0, 5000.0, 0.500, 0.0, 0.0, 10000.0, 10000.0, 0.000, 0.000, 0.000 )
    call BlzSetTerrainFogMaxLinearDensity( 1.0 )
    call BlzSetTerrainFogDrawOverSky( false )
    call SetHDWaterParamsEx( 0, 0, 0, true, 20, 20, 100, 10, 0, 50, 100, 100 )
    set we = AddWeatherEffect( Rect(-4096.0,-4096.0,4096.0,4096.0), 'VWbr' )
    call EnableWeatherEffect( we, true )
    call NewSoundEnvironment( "lake" )
    call SetAmbientDaySound( "IceCrownDay" )
    call SetAmbientNightSound( "IceCrownNight" )
    call SetMapMusic( "Music", true, 0 )
    call CreateAllUnits(  )
    call InitBlizzard(  )
    call InitGlobals(  )
    call InitCustomTriggers(  )
    call RunInitializationTriggers(  )

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName( "TRIGSTR_003" )
    call SetMapDescription( "TRIGSTR_005" )
    call SetPlayers( 6 )
    call SetTeams( 6 )
    call SetGamePlacement( MAP_PLACEMENT_TEAMS_TOGETHER )

    call DefineStartLocation( 0, -2368.0, 1472.0 )
    call DefineStartLocation( 1, 1905.9, 516.0 )
    call DefineStartLocation( 2, -1839.1, -2431.0 )
    call DefineStartLocation( 3, 978.8, -752.9 )
    call DefineStartLocation( 4, -1762.4, 1392.3 )
    call DefineStartLocation( 5, -1033.2, 1931.6 )

    // Player setup
    call InitCustomPlayerSlots(  )
    call InitCustomTeams(  )
    call InitAllyPriorities(  )
endfunction

